"""ai cluster

Revision ID: 20261001_0017
Revises: 20261001_0016
Create Date: 2026-10-01 09:07:27.784893
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20261001_0017'
down_revision: Union[str, Sequence[str], None] = '20261001_0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('model_id', sa.String(length=160), nullable=False),
    sa.Column('credential_ciphertext', sa.Text(), nullable=True),
    sa.Column('credential_key_version', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('max_daily_calls', sa.Integer(), nullable=False),
    sa.Column('allowed_tasks', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('openai','gemini','claude','openai_compatible','ollama','lm_studio')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ai_prompts',
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','tested','published','retired')"),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'locale', 'revision')
    )
    op.create_table('ai_routes',
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'priority'),
    sa.UniqueConstraint('task', 'provider_id')
    )
    op.create_table('ai_tenant_settings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_daily_calls', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'task')
    )
    op.create_table('ai_active_prompts',
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'locale')
    )
    op.create_table('ai_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_runs_organization_id'), ['organization_id'], unique=False)

    op.create_table('ai_progress_cache',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('viewer_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('route_digest', sa.String(length=64), nullable=False),
    sa.Column('highlight_ids', sa.JSON(), nullable=False),
    sa.Column('next_step', sa.String(length=32), nullable=False),
    sa.Column('ai_run_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id', 'organization_id'], ['ai_runs.id', 'ai_runs.organization_id']),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id']),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'viewer_id', 'scope', 'locale', 'source_digest', 'prompt_id', 'route_digest')
    )
    with op.batch_alter_table('ai_progress_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_progress_cache_organization_id'), ['organization_id'], unique=False)

    op.create_table('theme_selections',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id', 'organization_id'], ['student_profiles.id', 'student_profiles.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'student_id')
    )
    op.create_table('practice_questions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('ai_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('stem', sa.String(length=1000), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','hidden')"),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ),
    sa.ForeignKeyConstraint(['course_id', 'organization_id'], ['courses.id', 'courses.organization_id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id')
    )
    with op.batch_alter_table('practice_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_questions_organization_id'), ['organization_id'], unique=False)

    op.create_table('practice_attempts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('request_key', sa.Uuid(), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_day', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['question_id', 'organization_id'], ['practice_questions.id', 'practice_questions.organization_id'], ),
    sa.ForeignKeyConstraint(['student_id', 'organization_id'], ['student_profiles.id', 'student_profiles.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id'),
    sa.UniqueConstraint('organization_id', 'student_id', 'question_id'),
    sa.UniqueConstraint('organization_id', 'student_id', 'request_key')
    )
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_attempts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('practice_days',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('local_day', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id', 'organization_id'], ['practice_attempts.id', 'practice_attempts.organization_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id', 'organization_id'], ['student_profiles.id', 'student_profiles.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'student_id', 'local_day')
    )
    op.create_table('theme_grants',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('earned_day_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['earned_day_id'], ['practice_days.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id', 'organization_id'], ['student_profiles.id', 'student_profiles.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'student_id', 'theme')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Removing configured credentials, prompts, attempts or grants is destructive.
    for table in (
        'ai_providers', 'ai_prompts', 'ai_runs', 'ai_progress_cache', 'practice_questions',
        'practice_attempts', 'practice_days', 'theme_grants', 'theme_selections',
    ):
        if op.get_bind().execute(sa.text(f'SELECT 1 FROM {table} LIMIT 1')).first():
            raise RuntimeError(f'Cannot downgrade AI cluster with data in {table}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_grants')
    op.drop_table('practice_days')
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_practice_attempts_organization_id'))

    op.drop_table('practice_attempts')
    with op.batch_alter_table('practice_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_questions_organization_id'))

    op.drop_table('practice_questions')
    op.drop_table('theme_selections')
    with op.batch_alter_table('ai_progress_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_progress_cache_organization_id'))
    op.drop_table('ai_progress_cache')
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_runs_organization_id'))

    op.drop_table('ai_runs')
    op.drop_table('ai_active_prompts')
    op.drop_table('ai_tenant_settings')
    op.drop_table('ai_routes')
    op.drop_table('ai_prompts')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
