"""learning materials

Revision ID: 20261001_0016
Revises: 20260930_0015
Create Date: 2026-10-01 00:11:08.589424
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20261001_0016'
down_revision: Union[str, Sequence[str], None] = '20260930_0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'material_quotas',
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('quota_bytes', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.CheckConstraint('quota_bytes > 0 AND quota_bytes <= 2147483648'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id'),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curricula',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id')
    )
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curricula_organization_id'), ['organization_id'], unique=False)

    op.create_table('curriculum_versions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id', 'organization_id'], ['curricula.id', 'curricula.organization_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'revision'),
    sa.UniqueConstraint('id', 'organization_id')
    )
    op.create_table('curriculum_units',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id', 'organization_id'], ['curriculum_versions.id', 'curriculum_versions.organization_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['curriculum_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_version_id', 'position'),
    sa.UniqueConstraint('id', 'organization_id')
    )
    op.create_table('course_curricula',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id', 'organization_id'], ['courses.id', 'courses.organization_id'], ),
    sa.ForeignKeyConstraint(['curriculum_version_id', 'organization_id'], ['curriculum_versions.id', 'curriculum_versions.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'curriculum_version_id')
    )
    op.create_table('class_curricula',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id', 'organization_id'], ['learning_classes.id', 'learning_classes.organization_id'], ),
    sa.ForeignKeyConstraint(['curriculum_version_id', 'organization_id'], ['curriculum_versions.id', 'curriculum_versions.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'curriculum_version_id')
    )
    op.create_table('materials',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('withdrawn_reason', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("audience IN ('students','teachers')"),
    sa.CheckConstraint("scope IN ('library','class')"),
    sa.CheckConstraint("status IN ('draft','published','archived','withdrawn')"),
    sa.ForeignKeyConstraint(['class_id', 'organization_id'], ['learning_classes.id', 'learning_classes.organization_id'], ),
    sa.ForeignKeyConstraint(['session_id', 'class_id', 'organization_id'], ['class_sessions.id', 'class_sessions.class_id', 'class_sessions.organization_id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_organization_id'), ['organization_id'], unique=False)

    op.create_table('material_versions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file_status', sa.String(length=16), nullable=False),
    sa.Column('object_key', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('scan_message', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("file_status IN ('pending_check','ready','rejected')"),
    sa.CheckConstraint("kind IN ('pdf','image','audio','link')"),
    sa.CheckConstraint('size_bytes >= 0'),
    sa.ForeignKeyConstraint(['material_id', 'organization_id'], ['materials.id', 'materials.organization_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id'),
    sa.UniqueConstraint('material_id', 'revision'),
    sa.UniqueConstraint('organization_id', 'request_key'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('material_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_versions_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_versions_organization_id'), ['organization_id'], unique=False)

    op.create_table('curriculum_materials',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('material_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_hint', sa.String(length=100), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_version_id', 'organization_id'], ['material_versions.id', 'material_versions.organization_id'], ),
    sa.ForeignKeyConstraint(['unit_id', 'organization_id'], ['curriculum_units.id', 'curriculum_units.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'material_version_id')
    )
    op.create_table('material_assignments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('material_version_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('request_key', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id', 'organization_id'], ['learning_classes.id', 'learning_classes.organization_id'], ),
    sa.ForeignKeyConstraint(['material_version_id', 'organization_id'], ['material_versions.id', 'material_versions.organization_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id', 'class_id', 'organization_id'], ['class_sessions.id', 'class_sessions.class_id', 'class_sessions.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id'),
    sa.UniqueConstraint('organization_id', 'request_key')
    )
    with op.batch_alter_table('material_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_assignments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_assignments_organization_id'), ['organization_id'], unique=False)

    op.create_table('material_review_requests',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('material_version_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_version_id', 'organization_id'], ['material_versions.id', 'material_versions.organization_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_material_grants',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id', 'organization_id'], ['material_assignments.id', 'material_assignments.organization_id'], ),
    sa.ForeignKeyConstraint(['enrollment_id', 'organization_id'], ['enrollments.id', 'enrollments.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    for table in (
        'student_material_grants', 'material_review_requests', 'material_assignments',
        'curriculum_materials', 'material_versions', 'materials', 'class_curricula',
        'course_curricula', 'curriculum_units', 'curriculum_versions', 'curricula',
        'material_quotas',
    ):
        if connection.execute(sa.text(f'SELECT 1 FROM {table} LIMIT 1')).first():
            raise RuntimeError('Refusing to downgrade learning materials with data')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_material_grants')
    op.drop_table('material_review_requests')
    with op.batch_alter_table('material_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_assignments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_material_assignments_class_id'))

    op.drop_table('material_assignments')
    op.drop_table('curriculum_materials')
    with op.batch_alter_table('material_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_material_versions_material_id'))

    op.drop_table('material_versions')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_organization_id'))
        batch_op.drop_index(batch_op.f('ix_materials_class_id'))

    op.drop_table('materials')
    op.drop_table('class_curricula')
    op.drop_table('course_curricula')
    op.drop_table('curriculum_units')
    op.drop_table('curriculum_versions')
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curricula_organization_id'))

    op.drop_table('curricula')
    op.drop_table('material_quotas')
    # ### end Alembic commands ###
