import { test, expect } from '@playwright/test'

test('student registers, signs in, refreshes after reload, changes password and signs out', async ({ page, context }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await page.getByLabel('Họ và tên').fill('E2E Student')
  await page.getByLabel('Email', { exact: true }).fill('e2e-student@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-student-password!')
  await page.getByRole('combobox').selectOption({ label: 'Trung tâm Demo A' })
  await page.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Đã tạo tài khoản')
  await page.getByLabel('Email', { exact: true }).fill('e2e-student@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-student-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Thành viên', exact: true })).toHaveCount(0)
  const cookies = await context.cookies()
  expect(cookies.find(c => c.name === 'synapse_refresh')?.httpOnly).toBe(true)
  expect(await page.evaluate(() => localStorage.length)).toBe(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
  await page.getByLabel('Mật khẩu hiện tại').fill('e2e-student-password!')
  await page.getByLabel('Mật khẩu mới').fill('e2e-changed-password!')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Đăng nhập' })).toBeVisible()
  await page.getByLabel('Email', { exact: true }).fill('e2e-student@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-changed-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await page.getByRole('button', { name: 'Đăng xuất' }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Đăng nhập' })).toBeVisible()
})

test('root enters support session, creates a teacher, suspends membership and ends support', async ({ page, browser }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.getByLabel('Email', { exact: true }).fill('root@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-root-password-2026!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await page.getByRole('link', { name: 'Trung tâm' }).click()
  await page.getByLabel('Mở phiên hỗ trợ Trung tâm Demo A').fill('E2E support configuration')
  const center = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Trung tâm Demo A' }) })
  await center.getByRole('button', { name: 'Mở phiên hỗ trợ' }).click()
  await expect(page.getByText('Đang hỗ trợ trung tâm: Trung tâm Demo A')).toBeVisible()
  await page.getByRole('link', { name: 'Thành viên', exact: true }).click()
  const form = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Thêm thành viên' }) })
  await form.getByLabel('Họ và tên').fill('E2E Teacher')
  await form.getByLabel('Email', { exact: true }).fill('e2e-teacher@example.com')
  await form.getByLabel('Mật khẩu', { exact: true }).fill('e2e-teacher-password!')
  await form.getByLabel('Vai trò').selectOption('teacher')
  await form.getByLabel('Lý do').fill('E2E onboarding')
  await form.getByRole('button', { name: 'Tạo mới' }).click()
  const teacher = page.locator('article').filter({ has: page.getByRole('heading', { name: 'E2E Teacher' }) })
  await expect(teacher).toBeVisible()
  const teacherContext = await browser.newContext()
  const teacherPage = await teacherContext.newPage()
  await teacherPage.goto('http://127.0.0.1:5180/', { waitUntil: 'domcontentloaded' })
  await teacherPage.getByLabel('Email', { exact: true }).fill('e2e-teacher@example.com')
  await teacherPage.getByLabel('Mật khẩu', { exact: true }).fill('e2e-teacher-password!')
  await teacherPage.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(teacherPage.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
  const change = teacher.locator('form').first()
  await change.getByLabel('Hoạt động', { exact: true }).uncheck()
  await change.getByLabel('Lý do').fill('E2E suspension')
  await change.getByRole('button', { name: 'Lưu' }).click()
  await expect(teacher).toContainText('Tạm khóa')
  await teacherPage.reload()
  await expect(teacherPage.getByRole('heading', { name: 'Đăng nhập' })).toBeVisible()
  await teacherContext.close()
  await page.getByRole('button', { name: 'Kết thúc hỗ trợ' }).click()
  await expect(page.getByRole('link', { name: 'Thành viên', exact: true })).toHaveCount(0)
})
