import { test, expect } from '@playwright/test'

test('student registers, signs in, refreshes after reload, changes password and signs out', async ({ page, context }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await page.getByLabel('Họ và tên').fill('E2E Student')
  await page.getByLabel('Email', { exact: true }).fill('e2e-student@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-student-password!')
  await page.getByLabel('Nhập lại mật khẩu', { exact: true }).fill('e2e-student-password!')
  await page.getByRole('combobox').selectOption({ label: 'Trung tâm Demo A' })
  await page.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Đã tạo tài khoản')
  await page.getByLabel('Email', { exact: true }).fill('e2e-student@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-student-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Chào mừng trở lại/ })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Thành viên', exact: true })).toHaveCount(0)
  const cookies = await context.cookies()
  expect(cookies.find(c => c.name === 'synapse_refresh')?.httpOnly).toBe(true)
  expect(await page.evaluate(() => localStorage.length)).toBe(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: /Chào mừng trở lại/ })).toBeVisible()
  await page.locator('.dashboard-account summary').click()
  await page.getByLabel('Mật khẩu hiện tại').fill('e2e-student-password!')
  await page.getByLabel('Mật khẩu mới').fill('e2e-changed-password!')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Đăng nhập' })).toBeVisible()
  await page.getByLabel('Email', { exact: true }).fill('e2e-student@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-changed-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await page.getByRole('button', { name: 'Đăng xuất' }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Đăng nhập' })).toBeVisible()
})

test('root enters support session, creates a teacher, suspends membership and ends support', async ({ page, browser }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.getByLabel('Email', { exact: true }).fill('root@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-root-password-2026!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await page.getByRole('link', { name: 'Trung tâm' }).click()
  await page.getByLabel('Mở phiên hỗ trợ Trung tâm Demo A').fill('E2E support configuration')
  const center = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Trung tâm Demo A' }) })
  await center.getByRole('button', { name: 'Mở phiên hỗ trợ' }).click()
  await expect(page.getByText('Đang hỗ trợ trung tâm: Trung tâm Demo A')).toBeVisible()
  await page.getByRole('link', { name: 'Thành viên', exact: true }).click()
  const form = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Thêm thành viên' }) })
  await form.getByLabel('Họ và tên').fill('E2E Teacher')
  await form.getByLabel('Email', { exact: true }).fill('e2e-teacher@example.com')
  await form.getByLabel('Mật khẩu', { exact: true }).fill('e2e-teacher-password!')
  await form.getByLabel('Vai trò').selectOption('teacher')
  await form.getByLabel('Lý do').fill('E2E onboarding')
  await form.getByRole('button', { name: 'Tạo mới' }).click()
  const teacher = page.locator('article').filter({ has: page.getByRole('heading', { name: 'E2E Teacher' }) })
  await expect(teacher).toBeVisible()
  const teacherContext = await browser.newContext()
  const teacherPage = await teacherContext.newPage()
  await teacherPage.goto('http://127.0.0.1:5180/', { waitUntil: 'domcontentloaded' })
  await teacherPage.getByLabel('Email', { exact: true }).fill('e2e-teacher@example.com')
  await teacherPage.getByLabel('Mật khẩu', { exact: true }).fill('e2e-teacher-password!')
  await teacherPage.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(teacherPage.getByRole('heading', { name: /Chào mừng trở lại/ })).toBeVisible()
  const change = teacher.locator('form').first()
  await change.getByLabel('Hoạt động', { exact: true }).uncheck()
  await change.getByLabel('Lý do').fill('E2E suspension')
  await change.getByRole('button', { name: 'Lưu' }).click()
  await expect(teacher).toContainText('Tạm khóa')
  await teacherPage.reload()
  await expect(teacherPage.getByRole('heading', { name: 'Đăng nhập' })).toBeVisible()
  await teacherContext.close()
  await page.getByRole('button', { name: 'Kết thúc hỗ trợ' }).click()
  await expect(page.getByRole('link', { name: 'Thành viên', exact: true })).toHaveCount(0)
})

test('Soft auth stays usable across viewport, language and color settings', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Đăng nhập', exact: true })).toBeVisible()
  for (const width of [320, 390, 768, 1280, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    for (const colorScheme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme, reducedMotion: 'reduce' })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await expect(page.getByRole('button', { name: 'Đăng nhập', exact: true })).toBeInViewport()
      if ((width === 390 && colorScheme === 'dark') || (width === 1440 && colorScheme === 'light')) {
        await page.screenshot({ path: testInfo.outputPath(`auth-login-${width}-${colorScheme}.png`), fullPage: true })
      }
    }
  }
  await page.getByLabel('Email', { exact: true }).fill('learner@example.com')
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('learner@example.com')
  await page.getByLabel('Password', { exact: true }).fill('sample-password-only')
  await page.getByRole('button', { name: 'Show password: Password' }).click()
  await expect(page.getByLabel('Password', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Hide password: Password' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Register', exact: true }).click()
  await expect(page.getByRole('combobox')).toBeEnabled()
  await expect(page.getByLabel('Confirm password', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Register', exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Register', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('auth-register-mobile-dark.png'), fullPage: true })
  // A 640 CSS-pixel viewport represents the layout space of a 1280px window at 200% zoom.
  await page.setViewportSize({ width: 640, height: 450 })
  await page.getByLabel('Email', { exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Password', { exact: true })).toBeFocused()
  expect(await page.getByLabel('Password', { exact: true }).evaluate(el => getComputedStyle(el).outlineStyle)).toBe('solid')
  expect(await page.locator('.auth-orbit-core').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
})

test('welcome follows the actual profile load and preserves the requested page', async ({ page, request }, testInfo) => {
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  let holdProfile = false
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/v1/auth/me', async route => { if (holdProfile) await gate; await route.continue() })
  try {
    await page.goto('/sessions')
    await page.getByLabel('Email', { exact: true }).fill('root@example.com')
    await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-root-password-2026!')
    holdProfile = true
    await page.getByLabel('Mật khẩu', { exact: true }).press('Enter')
    await expect(page.getByRole('heading', { name: 'Đang chuẩn bị không gian học tập' })).toBeVisible()
    await expect(page.getByRole('status')).toContainText('Đang tải thông tin tài khoản')
    await expect(page.getByRole('navigation')).toHaveCount(0)
    await expect(page.locator('.auth-welcome')).toHaveCSS('opacity', '1')
    await page.screenshot({ path: testInfo.outputPath('auth-welcome-loading.png'), fullPage: true })
    release()
    await expect(page.getByRole('navigation').first()).toBeVisible()
    await expect(page).toHaveURL(/\/sessions$/)
    await expect(page.getByText('Đang hỗ trợ trung tâm:', { exact: false })).toHaveCount(0)
  } finally { release() }
})
