import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'

async function signIn(page: Page, email: string) {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill('class-module-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
  await page.getByRole('button', { name: 'English', exact: true }).click()
}

test('manager builds facilities and draft class; staff reads facilities and edits classes', async ({ page, browser, request }, testInfo) => {
  const base = 'http://127.0.0.1:8011/api/v1'
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  const common = { 'X-Synapse-Client': 'web', Origin: 'http://127.0.0.1:5180' }
  const login = await request.post(base + '/auth/login', { headers: common, data: { email: 'root@example.com', password: 'e2e-root-password-2026!' } })
  expect(login.ok()).toBe(true)
  const rootHeaders = { ...common, Authorization: `Bearer ${(await login.json()).access_token}` }
  const centers = await (await request.get(base + '/admin/organizations', { headers: rootHeaders })).json()
  const center = centers.find((x: { slug: string }) => x.slug === 'demo-a')
  const support = await (await request.post(base + '/admin/support-sessions', { headers: rootHeaders, data: { organization_id: center.id, reason: 'Class foundation fixtures' } })).json()
  const headers = { ...rootHeaders, 'X-Support-Session': support.id }
  async function create(path: string, data: object) {
    const response = await request.post(base + path, { headers, data })
    expect(response.ok(), `${path}: ${await response.text()}`).toBe(true)
    return response.json()
  }
  const lang = await create('/course-settings/languages', { code: 'CLS-EN', name: 'Class English' })
  const scale = await create('/course-settings/frameworks', { code: 'CLS-S', name: 'Class scale', language_id: lang.id })
  const level = await create('/course-settings/levels', { code: 'CLS-L1', name: 'Class level 1', framework_id: scale.id, rank: 1 })
  const course = await create('/courses', { code: 'CLS-COURSE', name: 'Foundation course', language_id: lang.id, framework_id: scale.id, exit_level_id: level.id, objectives: 'Original course goal' })
  await create(`/courses/${course.id}/state`, { version: 1, status: 'published', reason: 'Publish fixture' })
  for (const [email, role] of [['cls-manager@example.com', 'organization_manager'], ['cls-staff@example.com', 'staff']]) {
    await create('/members', { email, role, display_name: role, password: 'class-module-password!', reason: 'E2E fixture' })
  }
  await signIn(page, 'cls-manager@example.com')
  await page.getByRole('link', { name: 'Branches & rooms' }).click()
  await page.getByRole('button', { name: 'Add branch', exact: true }).click()
  await page.getByLabel('Code', { exact: true }).fill('CLS-MAIN')
  await page.getByLabel('Name', { exact: true }).fill('Foundation branch')
  await expect(page.getByLabel('IANA timezone')).toHaveValue('Asia/Ho_Chi_Minh')
  await page.getByLabel('Branch address').fill('Demo address')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Foundation branch', exact: true })).toBeVisible()
  const branches = await (await request.get(base + '/facilities/branches', { headers })).json()
  const branch = branches.items.find((x: { code: string }) => x.code === 'CLS-MAIN')
  await page.getByRole('button', { name: 'Rooms', exact: true }).click()
  await page.getByRole('button', { name: 'Add room', exact: true }).click()
  await page.getByLabel('Code', { exact: true }).fill('CLS-R01')
  await page.getByLabel('Name', { exact: true }).fill('Foundation room')
  await page.getByLabel('Managing branch').selectOption(branch.id)
  await page.getByLabel('Maximum capacity').fill('20')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Foundation room', exact: true })).toBeVisible()
  const rooms = await (await request.get(base + '/facilities/rooms', { headers })).json()
  const room = rooms.items.find((x: { code: string }) => x.code === 'CLS-R01')

  await page.getByRole('link', { name: 'Classes', exact: true }).click()
  await page.getByRole('button', { name: 'Create draft class', exact: true }).click()
  await page.getByLabel('Code', { exact: true }).fill('CLS-01')
  await page.getByLabel('Name', { exact: true }).fill('Foundation class')
  await page.getByLabel('Source course').selectOption(course.id)
  await page.getByLabel('Managing branch').selectOption(branch.id)
  await page.getByLabel('Default room').selectOption(room.id)
  await page.getByLabel('Maximum capacity').fill('21')
  await page.getByLabel('Planned start date').fill('2026-10-01')
  await page.getByLabel('Planned end date').fill('2026-12-01')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Class capacity exceeds the selected room capacity.')
  await page.getByLabel('Maximum capacity').fill('15')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Foundation class', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'View / edit', exact: true }).click()
  await expect(page.getByText('Original course goal', { exact: false })).toBeVisible()
  await expect(page.getByLabel('Source course')).toHaveCount(0)
  await page.getByRole('button', { name: 'Correct code', exact: true }).click()
  await page.getByLabel('Code', { exact: true }).fill('CLS-01-FIX')
  await page.getByLabel('Reason', { exact: true }).fill('Correct class code')
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByText('CLS-01-FIX · Draft', { exact: true })).toBeVisible()

  // Manager cannot shrink an occupied draft class room or archive it.
  await page.getByRole('link', { name: 'Branches & rooms' }).click()
  await page.getByRole('button', { name: 'Rooms', exact: true }).click()
  await page.getByRole('button', { name: 'View / edit', exact: true }).click()
  await page.getByLabel('Maximum capacity').fill('10')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Adjust the class first')
  await page.getByRole('button', { name: 'Archive', exact: true }).click()
  await page.getByLabel('Reason', { exact: true }).fill('Archive occupied room')
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('This facility has references')

  const staffContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5180' })
  const staff = await staffContext.newPage()
  await signIn(staff, 'cls-staff@example.com')
  await staff.getByRole('link', { name: 'Branches & rooms' }).click()
  await expect(staff.getByRole('heading', { name: 'Foundation branch' })).toBeVisible()
  await expect(staff.getByRole('button', { name: 'Add branch', exact: true })).toHaveCount(0)
  await staff.getByRole('button', { name: 'View / edit', exact: true }).click()
  await expect(staff.getByLabel('Branch address')).toBeDisabled()
  await expect(staff.getByRole('button', { name: 'Save', exact: true })).toHaveCount(0)
  await staff.getByRole('link', { name: 'Classes', exact: true }).click()
  await staff.getByRole('button', { name: 'View / edit', exact: true }).click()
  await staff.getByLabel('Class format').selectOption('online')
  await expect(staff.getByLabel('Default room')).toHaveValue('')
  await expect(staff.getByLabel('Default room')).toBeDisabled()
  await staff.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(staff.getByRole('heading', { name: 'Foundation class', exact: true })).toBeVisible()

  // The existing class keeps its original curriculum even if the source changes.
  await create(`/courses/${course.id}/state`, { version: 2, status: 'draft', reason: 'Edit source course' })
  const editedCourse = await request.patch(base + `/courses/${course.id}`, { headers, data: { version: 3, name: 'Changed source course', language_id: lang.id, framework_id: scale.id, exit_level_id: level.id, objectives: 'Changed course goal' } })
  expect(editedCourse.ok()).toBe(true)
  await staff.getByRole('button', { name: 'Refresh list', exact: true }).click()
  await staff.getByRole('button', { name: 'View / edit', exact: true }).click()
  await expect(staff.getByText('Original course goal', { exact: false })).toBeVisible()
  await expect(staff.getByText(/The source course is no longer published/)).toBeVisible()
  await staff.getByRole('button', { name: 'Archive', exact: true }).click()
  await staff.getByLabel('Reason', { exact: true }).fill('Archive test class')
  await staff.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(staff.getByRole('alert')).toHaveCount(0)
  await expect(staff.getByRole('button', { name: 'Search', exact: true })).toBeVisible()
  await staff.getByRole('combobox', { name: 'Status', exact: true }).selectOption('archived')
  await staff.getByRole('button', { name: 'Search', exact: true }).click()
  await staff.getByRole('button', { name: 'View / edit', exact: true }).click()
  await expect(staff.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
  await staff.getByRole('button', { name: 'Restore', exact: true }).click()
  await staff.getByLabel('Reason', { exact: true }).fill('Restore test class')
  await staff.getByRole('button', { name: 'Confirm', exact: true }).click()
  await staff.getByRole('combobox', { name: 'Status', exact: true }).selectOption('draft')
  await staff.getByRole('button', { name: 'Search', exact: true }).click()
  await staff.getByRole('button', { name: 'View / edit', exact: true }).click()
  await staff.getByRole('button', { name: 'Tiếng Việt', exact: true }).click()
  await staff.setViewportSize({ width: 390, height: 844 })
  for (const colorScheme of ['light', 'dark'] as const) {
    await staff.emulateMedia({ colorScheme })
    expect(await staff.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await staff.screenshot({ path: testInfo.outputPath(`classes-mobile-${colorScheme}.png`), fullPage: true })
  }
  await staffContext.close()
  expect((await request.delete(base + '/admin/support-sessions/' + support.id, { headers: rootHeaders })).ok()).toBe(true)
})
