import { test, expect } from '@playwright/test'

test('root configures levels and publishes a course; student sees only published courses', async ({ page, browser, request }) => {
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('root@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-root-password-2026!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await page.getByRole('link', { name: 'Trung tâm', exact: true }).click()
  const center = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Trung tâm Demo A', exact: true }) })
  await center.getByLabel('Mở phiên hỗ trợ Trung tâm Demo A').fill('Course catalog testing')
  await center.getByRole('button', { name: 'Mở phiên hỗ trợ' }).click()
  await page.getByRole('link', { name: 'Khóa học', exact: true }).click()
  await page.getByRole('button', { name: 'Ngôn ngữ và cấp độ', exact: true }).click()
  await page.getByLabel('Mã định danh').fill('EN')
  await page.getByLabel('Nhãn hiển thị').fill('Tiếng Anh')
  await page.getByRole('button', { name: 'Tạo mới', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tiếng Anh', exact: true })).toBeVisible()
  await page.getByLabel('Loại danh mục').selectOption('frameworks')
  await page.getByLabel('Mã định danh').fill('LOCAL')
  await page.getByLabel('Nhãn hiển thị').fill('Bộ cấp độ demo')
  await page.getByLabel('Ngôn ngữ đào tạo').selectOption({ label: 'Tiếng Anh (EN)' })
  await page.getByRole('button', { name: 'Tạo mới', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bộ cấp độ demo', exact: true })).toBeVisible()
  await page.getByLabel('Loại danh mục').selectOption('levels')
  await page.getByLabel('Mã định danh').fill('L1')
  await page.getByLabel('Nhãn hiển thị').fill('Cơ bản demo')
  await page.getByRole('combobox', { name: 'Bộ cấp độ', exact: true }).selectOption({ label: 'Bộ cấp độ demo (LOCAL) · Tiếng Anh' })
  await page.getByLabel('Thứ tự cấp độ').fill('1')
  await page.getByRole('button', { name: 'Tạo mới', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Cơ bản demo', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Về danh sách khóa học' }).click()
  await page.getByRole('button', { name: 'Tạo khóa học nháp', exact: true }).click()
  await page.getByLabel('Mã khóa học', { exact: true }).fill('DEMO-01')
  await page.getByLabel('Tên khóa học').fill('Khóa học thử nghiệm')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByText('Còn thiếu để công bố:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Công bố khóa học', exact: true }).click()
  await page.getByLabel('Lý do').fill('Test incomplete publication')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Chưa đủ thông tin công bố')
  await page.getByRole('button', { name: 'Hủy', exact: true }).click()
  await page.getByLabel('Ngôn ngữ đào tạo').selectOption({ label: 'Tiếng Anh (EN)' })
  await page.getByRole('combobox', { name: 'Bộ cấp độ', exact: true }).selectOption({ label: 'Bộ cấp độ demo (LOCAL)' })
  await page.getByRole('combobox', { name: 'Cấp độ đầu ra', exact: true }).selectOption({ label: 'Cơ bản demo (L1)' })
  await page.getByLabel('Mục tiêu học tập').fill('Mục tiêu minh họa, không phải quy chuẩn đào tạo.')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)

  const learnerContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5180' })
  const learner = await learnerContext.newPage()
  await learner.goto('/')
  await learner.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await learner.getByLabel('Họ và tên').fill('Course learner')
  await learner.getByLabel('Email', { exact: true }).fill('catalog-learner@example.com')
  await learner.getByLabel('Mật khẩu', { exact: true }).fill('catalog-learner-password!')
  await learner.getByRole('combobox').selectOption({ label: 'Trung tâm Demo A' })
  await learner.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await expect(learner.getByRole('status')).toContainText('Đã tạo tài khoản')
  await learner.getByLabel('Email', { exact: true }).fill('catalog-learner@example.com')
  await learner.getByLabel('Mật khẩu', { exact: true }).fill('catalog-learner-password!')
  await learner.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await learner.getByRole('link', { name: 'Danh mục khóa học', exact: true }).click()
  await expect(learner.getByRole('button', { name: 'Xem khóa học' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Công bố khóa học', exact: true }).click()
  await page.getByLabel('Lý do').fill('Publish test course')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Đưa về nháp', exact: true })).toBeVisible()
  await learner.getByRole('button', { name: 'Làm mới danh sách' }).click()
  await learner.getByLabel('Tìm mã hoặc tên khóa học').fill('DEMO-01')
  await learner.getByRole('button', { name: 'Tìm kiếm', exact: true }).click()
  await learner.getByRole('button', { name: 'Xem khóa học' }).click()
  await expect(learner.getByRole('heading', { name: 'Khóa học thử nghiệm', exact: true })).toBeVisible()
  await expect(learner.getByText('Mục tiêu minh họa, không phải quy chuẩn đào tạo.')).toBeVisible()
  await expect(learner.getByRole('button', { name: 'Công bố khóa học' })).toHaveCount(0)
  for (const [scheme, width] of [['dark', 390], ['light', 1280]] as const) {
    await learner.emulateMedia({ colorScheme: scheme })
    await learner.setViewportSize({ width, height: 900 })
    expect(await learner.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await learner.screenshot({ path: test.info().outputPath(`catalog-${scheme}.png`), fullPage: true })
  }
  await learner.getByRole('button', { name: 'English', exact: true }).click()
  await expect(learner.getByRole('heading', { name: 'Learning objectives' })).toBeVisible()
  await page.getByRole('button', { name: 'Lưu trữ khóa học', exact: true }).click()
  await page.getByLabel('Lý do').fill('Archive test course')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByText('DEMO-01 · Đã lưu trữ', { exact: true })).toBeVisible()
  await learner.getByRole('button', { name: 'Refresh list', exact: true }).click()
  await expect(learner.getByRole('alert')).toContainText('Course or setting not found')
  await expect(learner.getByRole('heading', { name: 'Khóa học thử nghiệm', exact: true })).toHaveCount(0)
  await learnerContext.close()
})

test('root corrects unused codes and confirms permanent deletion without cascading', async ({ page, request }) => {
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('root@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('e2e-root-password-2026!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await page.getByRole('link', { name: 'Trung tâm', exact: true }).click()
  const center = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Trung tâm Demo A', exact: true }) })
  await center.getByLabel('Mở phiên hỗ trợ Trung tâm Demo A').fill('Catalog maintenance test')
  await center.getByRole('button', { name: 'Mở phiên hỗ trợ' }).click()
  await page.getByRole('link', { name: 'Khóa học', exact: true }).click()
  await page.getByRole('button', { name: 'Ngôn ngữ và cấp độ', exact: true }).click()
  await page.getByLabel('Mã định danh').fill('TYPO')
  await page.getByLabel('Nhãn hiển thị').fill('Danh mục thử xóa')
  await page.getByRole('button', { name: 'Tạo mới', exact: true }).click()
  let item = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Danh mục thử xóa', exact: true }) })
  await item.getByRole('button', { name: 'Sửa mã', exact: true }).click()
  await item.getByLabel('Mã mới').fill('FIXED')
  await item.getByLabel('Lý do').fill('Sửa lỗi gõ mã thử nghiệm')
  await item.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(item.getByText('FIXED', { exact: true })).toBeVisible()
  await item.getByRole('button', { name: 'Xóa mục này', exact: true }).click()
  await expect(item.getByRole('button', { name: 'Xác nhận', exact: true })).toBeDisabled()
  await item.getByLabel('Nhập mã hiện tại để xác nhận xóa').fill('WRONG')
  await expect(item.getByRole('button', { name: 'Xác nhận', exact: true })).toBeDisabled()
  await item.getByRole('button', { name: 'Hủy', exact: true }).click()
  await expect(item.getByRole('heading', { name: 'Danh mục thử xóa', exact: true })).toBeVisible()
  await item.getByRole('button', { name: 'Xóa mục này', exact: true }).click()
  await item.getByLabel('Nhập mã hiện tại để xác nhận xóa').fill('FIXED')
  await item.getByLabel('Lý do').fill('Xóa dữ liệu thử chưa dùng')
  await item.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Đã xóa mục được xác nhận' })).toBeVisible()
  await expect(item).toHaveCount(0)
  // Build the referenced parent here so this scenario also runs independently.
  await page.getByLabel('Mã định danh').fill('PARENT')
  await page.getByLabel('Nhãn hiển thị').fill('Ngôn ngữ có bộ con')
  await page.getByRole('button', { name: 'Tạo mới', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ngôn ngữ có bộ con', exact: true })).toBeVisible()
  await page.getByLabel('Loại danh mục').selectOption('frameworks')
  await page.getByLabel('Mã định danh').fill('CHILD')
  await page.getByLabel('Nhãn hiển thị').fill('Bộ con thử nghiệm')
  await page.getByRole('combobox', { name: 'Ngôn ngữ đào tạo', exact: true }).selectOption({ label: 'Ngôn ngữ có bộ con (PARENT)' })
  await page.getByRole('button', { name: 'Tạo mới', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bộ con thử nghiệm', exact: true })).toBeVisible()
  await page.getByLabel('Loại danh mục').selectOption('languages')
  item = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Ngôn ngữ có bộ con', exact: true }) })
  await item.getByRole('button', { name: 'Xóa mục này', exact: true }).click()
  await item.getByLabel('Nhập mã hiện tại để xác nhận xóa').fill('PARENT')
  await item.getByLabel('Lý do').fill('Kiểm tra chặn xóa cha')
  await item.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(item.getByRole('alert')).toContainText('đã có bộ cấp độ hoặc cấp độ con')
  await item.getByRole('button', { name: 'Hủy', exact: true }).click()
  await page.getByRole('button', { name: 'Về danh sách khóa học' }).click()
  await page.getByRole('button', { name: 'Tạo khóa học nháp', exact: true }).click()
  await page.getByLabel('Mã khóa học', { exact: true }).fill('UNUSED')
  await page.getByLabel('Tên khóa học').fill('Khóa thử xóa')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await page.getByRole('button', { name: 'Sửa mã', exact: true }).click()
  await page.getByLabel('Mã mới').fill('UNUSED-FIXED')
  await page.getByLabel('Lý do').fill('Sửa mã khóa nháp thử')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByText('UNUSED-FIXED · Nháp', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Xóa mục này', exact: true }).click()
  await page.getByLabel('Nhập mã hiện tại để xác nhận xóa').fill('UNUSED-FIXED')
  await page.getByLabel('Lý do').fill('Xóa khóa tạo nhầm')
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.setViewportSize({ width: 390, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('delete-confirmation-dark.png'), fullPage: true })
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Đã xóa mục được xác nhận' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Khóa thử xóa', exact: true })).toHaveCount(0)
})
