import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'

async function signIn(page: Page, email: string) {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill('proficiency-test-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
}

test('student declares and sets goals; staff verifies and revokes with private evidence and public history', async ({ page, browser, request }) => {
  const base = 'http://127.0.0.1:8011/api/v1'
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  const common = { 'X-Synapse-Client': 'web', Origin: 'http://127.0.0.1:5180' }
  const login = await request.post(base + '/auth/login', { headers: common, data: { email: 'root@example.com', password: 'e2e-root-password-2026!' } })
  expect(login.ok()).toBe(true)
  const rootHeaders = { ...common, Authorization: `Bearer ${(await login.json()).access_token}` }
  const centers = await (await request.get(base + '/admin/organizations', { headers: rootHeaders })).json()
  const center = centers.find((x: { slug: string }) => x.slug === 'demo-a') || centers.find((x: { name: string }) => x.name === 'Trung tâm Demo A')
  const supportResponse = await request.post(base + '/admin/support-sessions', { headers: rootHeaders, data: { organization_id: center.id, reason: 'Proficiency fixture' } })
  expect(supportResponse.ok()).toBe(true)
  const support = await supportResponse.json()
  const headers = { ...rootHeaders, 'X-Support-Session': support.id }
  async function create(path: string, data: object) {
    const response = await request.post(base + path, { headers, data })
    expect(response.ok(), path).toBe(true)
    return response.json()
  }
  const lang = await create('/course-settings/languages', { code: 'PF-EN', name: 'Ngôn ngữ trình độ demo' })
  const framework = await create('/course-settings/frameworks', { code: 'PF-SCALE', name: 'Bộ trình độ demo', language_id: lang.id })
  await create('/course-settings/levels', { code: 'PF-L1', name: 'Mức một demo', rank: 1, framework_id: framework.id })
  await create('/course-settings/levels', { code: 'PF-L2', name: 'Mức hai demo', rank: 2, framework_id: framework.id })
  const student = await create('/members', { email: 'pf-student@example.com', display_name: 'PF Learner', password: 'proficiency-test-password!', role: 'student', reason: 'E2E fixture' })
  await create('/members', { email: 'pf-staff@example.com', display_name: 'PF Staff', password: 'proficiency-test-password!', role: 'staff', reason: 'E2E fixture' })
  await create('/students', { user_id: student.user_id, full_name: 'PF Learner' })
  await request.delete(base + '/admin/support-sessions/' + support.id, { headers: rootHeaders })
  await signIn(page, 'pf-student@example.com')
  await page.getByRole('link', { name: 'Hồ sơ học viên của tôi' }).click()
  await page.getByRole('button', { name: 'Trình độ và mục tiêu', exact: true }).click()
  await page.getByRole('combobox', { name: 'Ngôn ngữ đào tạo', exact: true }).selectOption({ label: 'Ngôn ngữ trình độ demo (PF-EN)' })
  await page.getByRole('combobox', { name: 'Bộ cấp độ', exact: true }).selectOption({ label: 'Bộ trình độ demo (PF-SCALE)' })
  await page.getByRole('button', { name: 'Thêm ngôn ngữ/bộ cấp độ', exact: true }).click()
  await page.getByRole('combobox', { name: 'Trình độ tự khai', exact: true }).selectOption({ label: 'Mức một demo (PF-L1)' })
  await page.getByRole('button', { name: 'Lưu tự khai', exact: true }).click()
  await expect(page.getByText('Trình độ tự khai: Mức một demo', { exact: false })).toBeVisible()
  await page.getByRole('textbox', { name: 'Mục tiêu học', exact: true }).fill('Ôn giao tiếp cơ bản')
  await page.getByRole('combobox', { name: 'Cấp độ mong muốn', exact: true }).selectOption({ label: 'Mức một demo (PF-L1)' })
  await page.getByRole('button', { name: 'Lưu mục tiêu', exact: true }).click()
  await expect(page.getByText('Mục tiêu học: Ôn giao tiếp cơ bản', { exact: true })).toBeVisible()
  const staffContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5180' })
  const staff = await staffContext.newPage()
  await signIn(staff, 'pf-staff@example.com')
  await staff.getByRole('link', { name: 'Học viên', exact: true }).click()
  await staff.getByLabel('Tìm theo mã hoặc tên học viên').fill('PF Learner')
  await staff.getByRole('button', { name: 'Tìm kiếm', exact: true }).click()
  await staff.getByRole('button', { name: 'Xem hồ sơ', exact: true }).click()
  await staff.getByRole('button', { name: 'Trình độ và mục tiêu', exact: true }).click()
  await staff.getByRole('button', { name: 'Xem trình độ và mục tiêu', exact: true }).click()
  await staff.getByRole('button', { name: 'Xác nhận/điều chỉnh trình độ', exact: true }).click()
  await staff.getByRole('combobox', { name: 'Cấp độ được xác nhận', exact: true }).selectOption({ label: 'Mức hai demo (PF-L2)' })
  await staff.getByLabel('Nguồn kiểm tra (nội bộ)').fill('PRIVATE-PF-SOURCE')
  await staff.getByLabel('Căn cứ kiểm tra (nội bộ)').fill('PRIVATE-PF-EVIDENCE')
  await staff.getByLabel('Lý do', { exact: true }).fill('PRIVATE-PF-REASON')
  await staff.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(staff.getByText('Trung tâm xác nhận: Mức hai demo', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Làm mới trình độ', exact: true }).click()
  await expect(page.getByText('Trung tâm xác nhận: Mức hai demo', { exact: false })).toBeVisible()
  await expect(page.getByText(/PRIVATE-PF/)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Xác nhận/điều chỉnh trình độ', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Trình độ tự khai', exact: true }).selectOption('')
  await page.getByRole('button', { name: 'Lưu tự khai', exact: true }).click()
  await expect(page.getByText('Trình độ tự khai: Chưa biết trình độ', { exact: false })).toBeVisible()
  await expect(page.getByText('Trung tâm xác nhận: Mức hai demo', { exact: false })).toBeVisible()
  await staff.getByRole('button', { name: 'Làm mới trình độ', exact: true }).click()
  await staff.getByRole('button', { name: 'Thu hồi xác nhận', exact: true }).click()
  await staff.getByLabel('Lý do', { exact: true }).fill('PRIVATE-PF-REVOKE')
  await staff.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(staff.getByText('Trung tâm xác nhận: Chưa có xác nhận hiện hành', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Làm mới trình độ', exact: true }).click()
  await expect(page.getByText('Trung tâm xác nhận: Chưa có xác nhận hiện hành', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Lịch sử trình độ/mục tiêu', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Thu hồi xác nhận · v/ })).toBeVisible()
  await expect(page.getByText(/PRIVATE-PF/)).toHaveCount(0)
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Proficiency and goals', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 900 })
  await page.emulateMedia({ colorScheme: 'light' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('proficiency-history-mobile.png'), fullPage: true })
  await staffContext.close()
})
