import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

async function signIn(page: Page, email: string) {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill('schedule-module-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
  await page.getByRole('button', { name: 'English', exact: true }).click()
}

test('staff previews and confirms schedules; clashes block reservations, adjacent sessions work, teacher sees own sessions', async ({ page, browser, request }, testInfo) => {
  const base = 'http://127.0.0.1:8011/api/v1'
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  const common = { 'X-Synapse-Client': 'web', Origin: 'http://127.0.0.1:5180' }
  const login = await request.post(base + '/auth/login', { headers: common, data: { email: 'root@example.com', password: 'e2e-root-password-2026!' } })
  expect(login.ok()).toBe(true)
  const rootHeaders = { ...common, Authorization: `Bearer ${(await login.json()).access_token}` }
  const centers = await (await request.get(base + '/admin/organizations', { headers: rootHeaders })).json()
  const center = centers.find((x: { slug: string }) => x.slug === 'demo-a')
  const support = await (await request.post(base + '/admin/support-sessions', { headers: rootHeaders, data: { organization_id: center.id, reason: 'Schedule fixtures' } })).json()
  const headers = { ...rootHeaders, 'X-Support-Session': support.id }
  async function create(path: string, data: object) {
    const response = await request.post(base + path, { headers, data })
    expect(response.ok(), `${path}: ${await response.text()}`).toBe(true)
    return response.json()
  }
  const language = await create('/course-settings/languages', { code: 'SCH-EN', name: 'Schedule English' })
  const scale = await create('/course-settings/frameworks', { code: 'SCH-S', name: 'Schedule scale', language_id: language.id })
  const level = await create('/course-settings/levels', { code: 'SCH-L1', name: 'Schedule level', framework_id: scale.id, rank: 1 })
  const course = await create('/courses', { code: 'SCH-COURSE', name: 'Schedule course', language_id: language.id, framework_id: scale.id, exit_level_id: level.id, objectives: 'Schedule testing' })
  await create(`/courses/${course.id}/state`, { version: 1, status: 'published', reason: 'Publish fixture' })
  const branch = await create('/facilities/branches', { code: 'SCH-B', name: 'Schedule branch' })
  const room = await create('/facilities/rooms', { branch_id: branch.id, code: 'SCH-R', name: 'Schedule room', capacity: 20 })
  for (const [email, role] of [['sch-teacher@example.com', 'teacher'], ['sch-staff@example.com', 'staff']]) await create('/members', { email, role, display_name: role, password: 'schedule-module-password!', reason: 'Fixture account' })
  const members = await (await request.get(base + '/members', { headers })).json()
  const teacherAccount = members.find((x: { email: string }) => x.email === 'sch-teacher@example.com')
  const teacher = await create('/teachers', { user_id: teacherAccount.user_id, full_name: 'Schedule Teacher', internal_notes: 'PRIVATE-SCHEDULE' })
  await create(`/teachers/${teacher.id}/capabilities`, { language_id: language.id, level_ids: [level.id], reason: 'Schedule capability' })
  const classes = []
  for (const code of ['SCH-A', 'SCH-B']) classes.push(await create('/classes', { code, name: code, course_id: course.id, branch_id: branch.id, room_id: room.id, capacity: 15, starts_on: '2026-10-01', ends_on: '2026-12-01', format: 'offline' }))
  await signIn(page, 'sch-staff@example.com')
  await page.getByRole('link', { name: 'Classes', exact: true }).click()
  async function openClass(code: string) {
    await page.getByLabel('Search code or name').fill(code)
    await page.getByRole('button', { name: 'Search', exact: true }).click()
    await page.getByRole('button', { name: 'Teachers & schedule', exact: true }).click()
    await expect(page.getByRole('heading', { name: `Teachers & schedule: ${code} (${code})` })).toBeVisible()
  }
  async function prepare() {
    await page.getByRole('checkbox', { name: 'Schedule Teacher · Matching capability recorded', exact: true }).check()
    await page.getByRole('button', { name: 'Save assignments', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Save schedule draft', exact: true })).toBeEnabled()
    await page.getByLabel('From date').fill('2026-10-05')
    await page.getByLabel('To date').fill('2026-10-05')
    await page.getByRole('button', { name: 'Save schedule draft', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Check and preview', exact: true })).toBeEnabled()
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click()
    await expect(page.getByText('Planned session count: 1 · Asia/Ho_Chi_Minh')).toBeVisible()
  }
  await openClass('SCH-A')
  await prepare()
  const before = await (await request.get(base + `/classes/${classes[0].id}/planning`, { headers })).json()
  expect(before.sessions).toHaveLength(0)
  await page.getByRole('button', { name: 'Confirm schedule', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByText(/Schedule confirmed; resources are reserved/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save schedule draft', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Refresh planning', exact: true }).click()
  await expect(page.getByText(/Schedule confirmed; resources are reserved/)).toBeVisible()
  await page.getByRole('button', { name: 'Back to list', exact: true }).click()
  await openClass('SCH-B')
  await prepare()
  await expect(page.getByText(/Room conflict.*SCH-A/)).toBeVisible()
  await expect(page.getByText(/Teacher conflict.*SCH-A/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Confirm schedule', exact: true })).toBeDisabled()
  await expect(page.getByRole('option', { name: /Schedule room.*Unavailable/ })).toHaveAttribute('disabled', '')
  await page.getByLabel('Start time').fill('19:30')
  await page.getByLabel('End time').fill('21:00')
  await page.getByRole('button', { name: 'Save schedule draft', exact: true }).click()
  await page.getByRole('button', { name: 'Check and preview', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Confirm schedule', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Confirm schedule', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByText(/Schedule confirmed; resources are reserved/)).toBeVisible()
  const teacherContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5180' })
  const personal = await teacherContext.newPage()
  await signIn(personal, 'sch-teacher@example.com')
  await personal.getByRole('link', { name: 'My teaching schedule', exact: true }).click()
  await expect(personal.getByRole('heading', { name: 'SCH-A (SCH-A)', exact: true })).toBeVisible()
  await expect(personal.getByRole('heading', { name: 'SCH-B (SCH-B)', exact: true })).toBeVisible()
  await expect(personal.getByRole('button', { name: 'Save assignments' })).toHaveCount(0)
  await expect(personal.getByText(/PRIVATE-SCHEDULE/)).toHaveCount(0)
  await personal.getByRole('button', { name: 'Tiếng Việt', exact: true }).click()
  await personal.setViewportSize({ width: 390, height: 844 })
  for (const colorScheme of ['light', 'dark'] as const) {
    await personal.emulateMedia({ colorScheme })
    expect(await personal.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await personal.screenshot({ path: testInfo.outputPath(`teaching-schedule-${colorScheme}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Tiếng Việt', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('confirmed-planning-dark.png'), fullPage: true })
  await teacherContext.close()
  expect((await request.delete(base + '/admin/support-sessions/' + support.id, { headers: rootHeaders })).ok()).toBe(true)
})
