import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'

async function signIn(page: Page, email: string, password: string) {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
}

test('staff creates student profile, student edits own contacts, archive keeps login active', async ({ page, browser, request }) => {
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  await signIn(page, 'root@example.com', 'e2e-root-password-2026!')
  await page.getByRole('link', { name: 'Trung tâm', exact: true }).click()
  const center = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Trung tâm Demo A', exact: true }) })
  await center.getByLabel('Mở phiên hỗ trợ Trung tâm Demo A').fill('Student profile testing')
  await center.getByRole('button', { name: 'Mở phiên hỗ trợ' }).click()
  await page.getByRole('link', { name: 'Thành viên', exact: true }).click()
  const form = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Thêm thành viên' }) })
  for (const [email, role, name] of [['profile-student@example.com', 'student', 'Profile learner'], ['profile-staff@example.com', 'staff', 'Profile staff']]) {
    await form.getByLabel('Họ và tên').fill(name)
    await form.getByLabel('Email', { exact: true }).fill(email)
    await form.getByLabel('Mật khẩu', { exact: true }).fill('profile-password-2026!')
    await form.getByLabel('Vai trò').selectOption(role)
    await form.getByLabel('Lý do').fill('Profile E2E fixture')
    await form.getByRole('button', { name: 'Tạo mới' }).click()
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click()
  await signIn(page, 'profile-staff@example.com', 'profile-password-2026!')
  await page.getByRole('link', { name: 'Học viên', exact: true }).click()
  await page.getByRole('button', { name: 'Tạo hồ sơ học viên', exact: true }).click()
  await page.getByLabel('Tìm tài khoản theo tên hoặc email').fill('profile-student@example.com')
  await page.getByRole('button', { name: 'Tìm kiếm', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Chọn tài khoản này' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Chọn tài khoản này' }).click()
  await page.getByLabel('Họ và tên', { exact: true }).fill('Học viên hồ sơ')
  await page.getByLabel('Số điện thoại', { exact: true }).fill('0901234567')
  await page.getByLabel('Ghi chú nội bộ (học viên không thấy)').fill('PRIVATE-STAFF-NOTE')
  await page.getByRole('button', { name: 'Thêm liên hệ' }).click()
  const guardian = page.getByRole('group', { name: 'Liên hệ 1', exact: true })
  await guardian.getByLabel('Họ và tên').fill('Người giám hộ')
  await guardian.getByLabel('Quan hệ với học viên').fill('Mẹ')
  await guardian.getByLabel('Số điện thoại').fill('0901234568')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Đã lưu thay đổi')
  const studentContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5180' })
  const learner = await studentContext.newPage()
  await signIn(learner, 'profile-student@example.com', 'profile-password-2026!')
  await learner.getByRole('link', { name: 'Hồ sơ học viên của tôi' }).click()
  await expect(learner.getByLabel('Ghi chú nội bộ (học viên không thấy)')).toHaveCount(0)
  await expect(learner.getByText('PRIVATE-STAFF-NOTE')).toHaveCount(0)
  await learner.getByLabel('Địa chỉ', { exact: true }).fill('Địa chỉ kiểm thử')
  await learner.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(learner.getByRole('status')).toContainText('Đã lưu thay đổi')
  // Staff still holds the prior version: stale writes must not overwrite the student's update.
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Hồ sơ đã thay đổi')
  await page.getByRole('button', { name: 'Làm mới danh sách' }).click()
  await expect(page.getByLabel('Địa chỉ')).toHaveValue('Địa chỉ kiểm thử')
  await expect(page.getByLabel('Ghi chú nội bộ (học viên không thấy)')).toHaveValue('PRIVATE-STAFF-NOTE')
  await page.getByRole('button', { name: 'Lưu trữ hồ sơ', exact: true }).click()
  await page.getByLabel('Lý do').fill('Archive profile test')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Khôi phục hồ sơ' })).toBeVisible()
  await learner.getByRole('button', { name: 'Làm mới danh sách' }).click()
  await expect(learner.getByRole('button', { name: 'Lưu', exact: true })).toBeDisabled()
  await expect(learner.getByRole('button', { name: 'Đăng xuất', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Về danh sách học viên' }).click()
  await page.getByLabel('Trạng thái hồ sơ').selectOption('archived')
  await page.getByLabel('Tìm theo mã hoặc tên học viên').fill('Học viên hồ sơ')
  await page.getByRole('button', { name: 'Tìm kiếm', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Học viên hồ sơ', exact: true })).toBeVisible()
  await studentContext.close()
})
