import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'

async function signIn(page: Page, email: string) {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill('teacher-module-password!')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng đến SynapseLMS' })).toBeVisible()
}

test('staff manages teacher profiles, capabilities and credentials; teacher sees only own public records', async ({ page, browser, request }) => {
  const base = 'http://127.0.0.1:8011/api/v1'
  await request.post('http://127.0.0.1:8011/__test/reset-rate')
  const common = { 'X-Synapse-Client': 'web', Origin: 'http://127.0.0.1:5180' }
  const login = await request.post(base + '/auth/login', { headers: common, data: { email: 'root@example.com', password: 'e2e-root-password-2026!' } })
  expect(login.ok()).toBe(true)
  const rootHeaders = { ...common, Authorization: `Bearer ${(await login.json()).access_token}` }
  const centers = await (await request.get(base + '/admin/organizations', { headers: rootHeaders })).json()
  const center = centers.find((x: { slug: string }) => x.slug === 'demo-a')
  const supportResponse = await request.post(base + '/admin/support-sessions', { headers: rootHeaders, data: { organization_id: center.id, reason: 'Teacher fixtures' } })
  expect(supportResponse.ok()).toBe(true)
  const support = await supportResponse.json()
  const headers = { ...rootHeaders, 'X-Support-Session': support.id }
  async function create(path: string, data: object) {
    const response = await request.post(base + path, { headers, data })
    expect(response.ok(), path).toBe(true)
    return response.json()
  }
  const lang = await create('/course-settings/languages', { code: 'TCH-EN', name: 'Ngôn ngữ giáo viên demo' })
  const scale = await create('/course-settings/frameworks', { code: 'TCH-S', name: 'Bộ giáo viên demo', language_id: lang.id })
  for (const rank of [1, 2]) await create('/course-settings/levels', { code: `TCH-L${rank}`, name: `Cấp giáo viên ${rank}`, framework_id: scale.id, rank })
  await create('/members', { email: 'tch-module@example.com', display_name: 'Teacher Module', password: 'teacher-module-password!', role: 'teacher', reason: 'E2E fixture' })
  await create('/members', { email: 'tch-staff@example.com', display_name: 'Teacher Staff', password: 'teacher-module-password!', role: 'staff', reason: 'E2E fixture' })
  expect((await request.delete(base + '/admin/support-sessions/' + support.id, { headers: rootHeaders })).ok()).toBe(true)

  const teacherContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5180' })
  const teacher = await teacherContext.newPage()
  await signIn(teacher, 'tch-module@example.com')
  await teacher.getByRole('link', { name: 'Hồ sơ giáo viên của tôi' }).click()
  await expect(teacher.getByText('Trung tâm chưa tạo hồ sơ giáo viên cho bạn. Vui lòng liên hệ giáo vụ.')).toBeVisible()
  await signIn(page, 'tch-staff@example.com')
  await page.getByRole('link', { name: 'Giáo viên', exact: true }).click()
  await page.getByRole('button', { name: 'Tạo hồ sơ giáo viên' }).click()
  await page.getByLabel('Tìm giáo viên theo tên hoặc email').fill('tch-module@example.com')
  await page.getByRole('button', { name: 'Tìm kiếm', exact: true }).click()
  await page.getByRole('button', { name: 'Chọn tài khoản này' }).click()
  await page.getByLabel('Họ và tên', { exact: true }).fill('Giáo viên kiểm thử')
  await page.getByLabel('Ghi chú nội bộ (giáo viên không thấy)').fill('PRIVATE-TCH-PROFILE')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Giáo viên kiểm thử', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Năng lực giảng dạy', exact: true }).click()
  await page.getByRole('button', { name: 'Thêm năng lực giảng dạy', exact: true }).click()
  await page.getByRole('combobox', { name: 'Ngôn ngữ đào tạo' }).selectOption(lang.id)
  await page.getByRole('checkbox', { name: 'Bộ giáo viên demo · Cấp giáo viên 2 (TCH-L2)' }).check()
  await page.getByLabel('Lý do', { exact: true }).fill('PRIVATE-TCH-REASON')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('listitem')).toHaveText(['Bộ giáo viên demo (TCH-S) · Cấp giáo viên 2 (TCH-L2)'])
  await page.getByRole('button', { name: 'Chứng chỉ', exact: true }).click()
  await page.getByRole('button', { name: 'Thêm chứng chỉ', exact: true }).click()
  await page.getByLabel('Tên chứng chỉ').fill('Chứng chỉ kiểm thử')
  await page.getByLabel('Đơn vị cấp').fill('Demo issuer')
  await page.getByLabel('Ngày cấp').fill('2020-01-01')
  await page.getByLabel('Ngày hết hạn').fill('2021-01-01')
  await page.getByLabel('Ghi chú nội bộ (giáo viên không thấy)').fill('PRIVATE-TCH-CERT')
  await page.getByLabel('Lý do', { exact: true }).fill('PRIVATE-TCH-CERT-REASON')
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByText('Chứng chỉ đã hết hạn; năng lực giảng dạy không tự bị thu hồi.')).toBeVisible()

  await teacher.getByRole('button', { name: 'Làm mới hồ sơ giáo viên' }).click()
  await expect(teacher.getByText(/PRIVATE-TCH/)).toHaveCount(0)
  await teacher.getByLabel('Số điện thoại').fill('0900000000')
  await teacher.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(teacher.getByRole('status')).toContainText('Đã lưu thay đổi')
  await teacher.getByRole('button', { name: 'Năng lực giảng dạy', exact: true }).click()
  await expect(teacher.getByRole('listitem')).toHaveText(['Bộ giáo viên demo (TCH-S) · Cấp giáo viên 2 (TCH-L2)'])
  await expect(teacher.getByRole('button', { name: 'Sửa / thu hồi bản ghi' })).toHaveCount(0)
  await teacher.getByRole('button', { name: 'Chứng chỉ', exact: true }).click()
  await expect(teacher.getByText('Chứng chỉ đã hết hạn; năng lực giảng dạy không tự bị thu hồi.')).toBeVisible()
  await expect(teacher.getByText(/PRIVATE-TCH/)).toHaveCount(0)
  await teacher.getByRole('button', { name: 'Lịch sử năng lực / chứng chỉ', exact: true }).click()
  await expect(teacher.getByRole('heading', { name: 'Tạo bản ghi · v1' })).toHaveCount(2)
  await expect(teacher.getByText(/PRIVATE-TCH/)).toHaveCount(0)

  await page.getByRole('button', { name: 'Năng lực giảng dạy', exact: true }).click()
  await page.getByRole('button', { name: 'Sửa / thu hồi bản ghi', exact: true }).click()
  await page.getByRole('button', { name: 'Thu hồi bản ghi', exact: true }).click()
  await page.getByLabel('Lý do', { exact: true }).fill('PRIVATE-TCH-REVOKE')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByText('Trung tâm ghi nhận thủ công · Đã thu hồi')).toBeVisible()
  await teacher.getByRole('button', { name: 'Năng lực giảng dạy', exact: true }).click()
  await expect(teacher.getByText('Trung tâm ghi nhận thủ công · Đã thu hồi')).toBeVisible()

  await page.getByRole('button', { name: 'Hồ sơ', exact: true }).click()
  await page.getByRole('button', { name: 'Lưu', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Dữ liệu đã thay đổi')
  await page.getByRole('button', { name: 'Làm mới hồ sơ giáo viên' }).click()
  await expect(page.getByLabel('Số điện thoại')).toHaveValue('0900000000')
  await page.getByRole('button', { name: 'Lưu trữ hồ sơ', exact: true }).click()
  await page.getByLabel('Lý do', { exact: true }).fill('Archive teacher test')
  await page.getByRole('button', { name: 'Xác nhận', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Khôi phục hồ sơ', exact: true })).toBeVisible()
  await teacher.getByRole('button', { name: 'Làm mới hồ sơ giáo viên' }).click()
  await teacher.getByRole('button', { name: 'Hồ sơ', exact: true }).click()
  await expect(teacher.getByRole('button', { name: 'Lưu', exact: true })).toBeDisabled()
  await teacher.getByRole('button', { name: 'English', exact: true }).click()
  await expect(teacher.getByRole('heading', { name: 'My teacher profile', exact: true })).toBeVisible()
  await teacher.setViewportSize({ width: 390, height: 900 })
  for (const theme of ['light', 'dark'] as const) {
    await teacher.emulateMedia({ colorScheme: theme })
    expect(await teacher.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await teacher.screenshot({ path: test.info().outputPath(`teacher-profile-${theme}.png`), fullPage: true })
  }
  await teacherContext.close()
})
